// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Error": {
    "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
    "title": "Something went wrong!"
  },
  "IndexPage": {
    "description": "Turkish Club Turkish Club, Münih’teki Türk öğrencileri bir araya getirmeyi amaçlayan, üniversite temelli bağımsız bir öğrenci topluluğudur. Kültürel bağlarımızı güçlendirirken yeni gelenlere destek olur, sosyal ve akademik dayanışmayı teşvik ederiz.",
    "title": "Turkish Club"
  },
  "LocaleLayout": {
    "title": "Turkish Club",
    "description": "Turkish Club is an independent university-based student community that aims to bring together Turkish students in Munich. We strengthen our cultural bonds while supporting newcomers and promoting social and academic solidarity."
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, de {Deutsch} en {English} tr {Türkçe} other {Unknown}}"
  },
  "Manifest": {
    "name": "next-intl example"
  },
  "Navigation": {
    "home": "Home",
    "pathnames": "Pathnames"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "PageLayout": {
    "links": {
      "docs": {
        "description": "Learn more about next-intl in the official docs.",
        "href": "https://next-intl.dev",
        "title": "Docs"
      },
      "source": {
        "description": "Browse the source code of this example on GitHub.",
        "href": "https://github.com/amannn/next-intl/tree/main/examples/example-app-router",
        "title": "Source code"
      }
    }
  },
  "PathnamesPage": {
    "description": "<p>The pathnames are internationalized too.</p><p>If you're using the default language English, you'll see <code>/en/pathnames</code> in the browser address bar on this page.</p><p>If you change the locale to German, the URL is localized accordingly (<code>/de/pfadnamen</code>).</p>",
    "title": "Pathnames"
  },

  "HomePage": {
    "hero": {
      "title": "Turkish Club",
      "subtitle": "Munich Turkish Student Community",
      "joinButton": "Join Us!"
    },
    "poll": {
      "question": "What would you like to see in the Turkish Club?"
    }
  },
    "Navbar": {
    "joinTeam": "Join Team",
    "platforms": "Platforms",
    "platformsDesc": "Our social media accounts",
    "tools": "Tools",
    "toolsDesc": "Useful tools and resources",
    "pages": "Pages",
    "pagesDesc": "About us and content",
    "instagram": "Instagram",
    "instagramDesc": "Latest posts and events",
    "github": "GitHub",
    "githubDesc": "Our open source projects",
    "whatsapp": "WhatsApp",
    "whatsappDesc": "Community chat group",
    "dormSearch": "Dorm Search",
    "dormSearchDesc": "Page where we organize dormitories for those seeking housing in Munich.",
    "studyPlaceSearch": "Study Place Search",
    "studyPlaceSearchDesc": "Find suitable places to study in Munich",
    "blog": "Blog",
    "blogDesc": "Latest articles and news",
    "team": "Team",
    "teamDesc": "Our team and open positions"
  },
  
  "FAQ" : {
    "title": "FAQ",
    "questions": [
    {
      "question": "What is Turkish Club?",
      "answer": "Munich Turkish Student Club is a student-focused community that brings together Turkish students living and studying in Munich. Our main goal is to support each other, create a sense of belonging abroad, and organize activities that unite students socially, academically, and culturally."
    },
    {
      "question": "Is the club only for university students?",
      "answer": "No, our club is not only for university students. All Turkish youth and students living in Munich can join us."
    },
    {
      "question": "What kind of events do you organize?",
      "answer": "We organize cultural events, social gatherings, academic seminars, sports activities, and various celebrations."
    },
    {
      "question": "What are the rules of Turkish Club?",
      "answer": "Our club's basic rules are built on respect, tolerance, and unity. For detailed rules, you can contact our team."
    }
    ]
  },
  "dormSearch": {
    "title": "Dorm Search",
    "subtitle": "Student housing options for Turkish students in Munich",
    "description": "Discover dormitories and student housing that Turkish students in Munich can apply to. Filter by price, location, and features.",
    "suggestDorm": {
      "button": "Suggest a Dorm",
      "description": "Know a dorm we should list? Share your suggestion with us!"
    },
    "search": {
      "placeholder": "Search dorm name or address...",
      "button": "Search"
    },
    "filters": {
      "title": "Filters",
      "priceRange": "Price Range",
      "maxPrice": "Maximum Price",
      "location": "Location",
      "features": "Features",
      "clearAll": "Clear All",
      "apply": "Apply"
    },
    "sort": {
      "label": "Sort by",
      "price_asc": "Price (Low to High)",
      "price_desc": "Price (High to Low)",
      "name": "Name (A-Z)",
      "distance": "Distance"
    },
    "card": {
      "rent": "Rent",
      "monthly": "monthly",
      "monthlyPrice": "monthly",
      "address": "Address",
      "website": "Website",
      "visitWebsite": "Visit Website",
      "viewOnMap": "View on Map",
      "moreInfo": "More Details",
      "applyNow": "Apply Now",
      "features": "Features",
      "showLess": "Show Less",
      "readMore": "Read More",
      "university": {
        "gfz": "Garching FZ",
        "mainCampus": "Main Campus",
        "minutes": "min"
      }
    },
    "map": {
      "title": "Map View",
      "showList": "List View",
      "showMap": "Map View",
      "showingLocations": "Showing {count} dorm locations",
      "popup": {
        "moreInfo": "More Details",
        "visitWebsite": "Visit Website",
        "getDirections": "Get Directions"
      }
    },
    "results": {
      "showing": "Showing {filtered} of {total} dorms",
      "noResults": "No dorms found matching your search criteria.",
      "foundResults": "{count} dorms found",
      "adjustFilters": "Try adjusting your search criteria."
    }
  },
  "team": {
    "hero": {
      "title": {
        "prefix": "At Turkish Club"
      },
      "animate": {
        "code": "Code",
        "blog": "Write Blog",
        "design": "Design"
      },
      "description": "Help us build the strongest Turkish community in Munich. Join our team and make a meaningful impact while developing your skills and connecting with amazing people."
    },
    "positions": {
      "subtitle": "Job openings",
      "title": "Open Positions",
      "description": "We are always looking for talented individuals to join our team. Below are some of the roles we are currently hiring for."
    },
    "search": {
      "placeholder": "Search positions..."
    },
    "filter": {
      "button": "Filter",
      "title": "Filter Positions",
      "clearAll": "Clear all",
      "department": "Department",
      "jobType": "Job Type",
      "location": "Location"
    },
    "results": {
      "showing": "Showing {filtered} of {total} positions",
      "noResults": "No positions found matching your criteria."
    }
  },
  "blog": {
    "title": "Blog",
    "description": "Stay updated with the latest news, insights, and stories from the Turkish community.",
    "search": {
      "placeholder": "Search blog posts...",
      "button": "Search"
    },
    "filters": {
      "all": "All",
      "recent": "Recent Posts",
      "popular": "Popular"
    },
    "readTime": "min read",
    "readMore": "Read More",
    "noResults": "No blog posts found matching your search criteria.",
    "loading": "Loading...",
    "results": {
      "showing": "Showing {count} articles",
      "noArticles": "No articles found",
      "noResultsFor": "No results for \"{searchTerm}\"",
      "adjustFilters": "Try adjusting your search or filter criteria",
      "clearFilters": "Clear Filters"
    },
    "sort": {
      "newest": "Newest First",
      "oldest": "Oldest First",
      "popular": "Most Popular"
    }
  }
};
export default messages;